name: File Path Validation
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check file paths
        uses: actions/checkout@v2
        
      - name: Validate paths
        run: |
          # Regular expression pattern for validating file paths
          pattern='^[0-9a-z_.\-/]+$'
          
          # Get the list of modified files in the PR
          files=$(git diff --name-only HEAD $(git merge-base HEAD ${{ github.base_ref }}))
          
          # Check each file path
          for file in $files; do
            if ! [[ $file =~ $pattern ]]; then
              echo "Invalid file path: $file"
              exit 1
            fi
          done