name: Pull Request Check
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PR check
        run: |
          # 获取基准分支名称
          base_branch=$(git rev-parse --abbrev-ref HEAD)

          # 获取修改的文件路径
          files=$(git diff --name-only $base_branch...HEAD)

          # 设置需要匹配的正则表达式
          regex='^[0-9a-z_.-]+$'

          # 检查文件路径是否符合正则表达式
          if [[ $files =~ $regex ]]; then
            echo "File paths match the regex pattern. Check passed."
          else
            echo "File paths do not match the regex pattern. Check failed."
            exit 1
          fi