name: Add Size Labels
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Count lines of code
        id: count_lines
        run: |
          # Count lines of code changed in the pull request
          lines=$(git diff --shortstat origin/main ${{ github.event.pull_request.head.ref }} | awk '{print $1 + $4}')
          echo "::set-output name=lines::$lines"
      
      - name: Add label
        uses: actions/github-script@v4
        with:
          script: |
            const lines = parseInt(process.env.lines);
            let label = '';
            
            if (lines >= 1 && lines <= 100) {
              label = 'small';
            } else if (lines >= 101 && lines <= 1000) {
              label = 'medium';
            } else if (lines > 1000) {
              label = 'large';
            }
            
            if (label) {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
