name: Label PR by Lines

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Count lines in PR
        id: lines
        run: echo "::set-output name=lines::$(git diff --shortstat $(git merge-base origin/main ${{ github.event.pull_request.head.ref }})..${{ github.event.pull_request.head.ref }} | grep -Eo '([0-9]+) insertions?' | grep -Eo '[0-9]+')"

      - name: Add label based on lines
        uses: actions/github-script@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const lines = parseInt('${{ steps.lines.outputs.lines }}');
            let label = '';

            if (lines <= 100) {
              label = 'small';
            } else if (lines <= 1000) {
              label = 'medium';
            } else {
              label = 'large';
            }

            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            });
