name: Comment PR Files

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment_pr_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        id: filelist
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }})"

      - name: Comment PR files
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const files = `${{ steps.filelist.outputs.files }}`.split("\n");
            const issueComment = await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Files in this pull request:\n\n" + files.map(file => `- ${file}`).join("\n")
            });
            console.log(`Commented with files: ${files}`);