name: List Files in PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in PR
        id: list_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only FETCH_HEAD ${{ github.sha }} > file_list.txt
          echo "::set-output name=file_list_path::file_list.txt"
          
      - name: Use file list
        run: |
          file_list_path=$(cat ${{ steps.list_files.outputs.file_list_path }})
          cat ${{ file_list_path }}