name: List Files in PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in PR
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only FETCH_HEAD ${{ github.sha }}