name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Calculate number of lines
        id: lines
        run: echo "::set-output name=lines::$(git diff --shortstat origin/${{ github.base_ref }}...${{ github.head_ref }} | sed 's/[^0-9-]*//g' | awk '{s+=$1} END {print s}')"

      - name: Label pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const lines = parseInt('${{ steps.lines.outputs.lines }}');
            let label;
            if (lines <= 100) {
              label = 'small';
            } else if (lines <= 1000) {
              label = 'medium';
            } else {
              label = 'large';
            }
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            });