name: PR Size Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
             npm install @actions/github
             npm install @actions/core
             npm install @octokit/rest
      

      - name: Run PR Size Labeler
        run: node pr-size-labeler.js
        env:
          PR_SIZE: ${{ steps.setup.outputs.PR_SIZE }}

      - name: Create/Update PR Label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prSize = process.env.PR_SIZE;
            let label = '';
      
            if (prSize <= 100) {
              label = 'small';
            } else if (prSize <= 1000) {
              label = 'medium';
            } else {
              label = 'large';
            }
      
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
      
            octokit.issues.addLabels({
              owner: process.env.GITHUB_REPOSITORY_OWNER,
              repo: process.env.GITHUB_REPOSITORY,
              issue_number: process.env.GITHUB_ISSUE_NUMBER,
              labels: [label]
            });