name: Pull Request Size Labeler
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Count changed lines
        id: count_lines
        run: echo "::set-output name=lines::$(git diff --shortstat $(git merge-base origin/main ${{ github.event.pull_request.head.ref }}) ${{ github.event.pull_request.head.sha }} | awk '{print $1+$4+$7}')"

      - name: Add size label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const lines = parseInt('${{ steps.count_lines.outputs.lines }}');
            let label = '';
            
            if (lines >= 1 && lines <= 100) {
              label = 'small';
            } else if (lines > 100 && lines <= 1000) {
              label = 'medium';
            } else if (lines > 1000) {
              label = 'large';
            }

            if (label !== '') {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }